[package]
name = "enums"
version = "0.1.0"
authors = ["Richard Roncancio <batusai513@msn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
